NAME = "clash roYale"
TILE_SIZE = 20
CARD_WIDTH = 70
CARD_HEIGHT = 100
WIDTH = 22 * TILE_SIZE 
HEIGHT = 36 * TILE_SIZE
FPS = 60
ASSETS_PATH = "assets/sprites/arena/"
COVER_PATH = "assets/covers"
ARENA_PATH = "data/"
DECK_PATH = "data/deck.json"
